Initial Pomodoro Timer
robynsmith/brain-cycle pull request #1
Opened 2016-11-16 15:59 UTC by robynsmith

Hopefully can gather feedback.

2016-11-17 02:47 UTC, wcarss commented on main.js
> +          timeSec = 0;
indentation issues all over :P

2016-11-17 02:55 UTC, wcarss requested changes
- imo indentation is easy to fix and important even in your own code
- global vars ew, but, understandable and probablyt he simplest option for this use case
- cool story bro

2016-11-17 02:55 UTC, wcarss commented on main.js
> +	$("button").click(function() {
classes or ids for different button actions and having multiple registered functions would eliminate the need for a switch statement in here

2016-11-17 02:55 UTC, wcarss commented on main.js
> +  $("").html(displayString);
what is `$("")`

2016-11-17 02:55 UTC, wcarss commented on main.js
> +	if (timeSec === 0) {
could < 0 in case something external modifies it between calls

2017-02-06 17:19 UTC, closed without merging

2017-02-06 19:39 UTC, wcarss commented
booo closed without merge bad maintenance

2017-02-07 15:38 UTC, robynsmith commented
@wcarss The lulz.

Just clearing out my "Pull Requests" page of things I'm not actively working on.